import * as React from 'react'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'
import { Provider as BalancerProvider } from 'react-wrap-balancer'
import { getTranslation } from '@/i18n'
import { TranslationProvider } from '@/components/translate/translations-provider'
import { Toaster } from '@/components/toaster'
import { ThemeProvider } from '@/components/theme-provider'
import { cn } from '@/components/lib/utils'
import { Indicators } from '@/components/indicators/indicator'

import '@/app/[locale]/global.css'
import { PageParams } from '@/types'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export interface RootLayoutProps {
  children: React.ReactNode
  params: PageParams
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  /* TODO: if local not exist redirect to default.
   * Can't use useLocal from next-inlt.
   * May read files in translation folder
   */

  const session = await getServerSession()
  const isLoggedIn = Boolean(session)

  return (
    <html lang={params.locale} suppressHydrationWarning>
      <body
        className={cn(
          inter.className,
          'w-full min-h-screen bg-background font-sans antialiased'
        )}
      >
        <TranslationProvider
          locale={params.locale}
          getTranslation={getTranslation}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <BalancerProvider>
              {children}
              <Toaster />
              <Indicators isLoggedIn={isLoggedIn} />
            </BalancerProvider>
          </ThemeProvider>
        </TranslationProvider>
      </body>
    </html>
  )
}
